### ISSUE TITLE
更新新的镜像后,docker启动失败

### ISSUE THREAD

**Issue by 765741668** [linweiyuan/java-chatgpt-api#1]
配置:
services:
  java-chatgpt-api:
    container_name: java-chatgpt-api
    image: linweiyuan/java-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - CHATGPT=true
      - PROXY=
    restart: unless-stopped

启动:
docker-compose up -d

报错:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7048170/230500236-02cf325e-9147-4a2f-b3db-aa4504a68f5e.png">

**Comment by linweiyuan** [comment]
已修复，需要重新拉下镜像
