### ISSUE TITLE
本地127.0.0.1:8080服务拒绝 

### ISSUE THREAD

**Issue by lmq-118** [linweiyuan/java-chatgpt-api#11]
本地127.0.0.1:8080服务拒绝 无法接收到请求，没有日志
接口调用显示：
request to http://127.0.0.1:8080/conversation failed, reason: connect ECONNREFUSED 127.0.0.1:8080

外部访问可以打印出日志，这是什么情况呢

**Comment by linweiyuan** [comment]
127.0.0.1 指向的是自己的地址

在容器里就指向容器自己

而不是其他 8080 服务

**Comment by lmq-118** [comment]
不好意思，进错地方了，我是 docker中启的2个compose ：1.反向代理用的 go-chatGpt-api那个项目，2 结合chatGpt-web，前端发起聊天后，反向代理后端貌似没有收到请求，也没看到请求日志，我开放端口后通过域名在外部浏览器访问，可以收到api中的请求日志
![image](https://user-images.githubusercontent.com/25766225/235069850-047f8f03-d87a-4da6-be1c-cd4fae125410.png)
![image](https://user-images.githubusercontent.com/25766225/235070678-89aaa915-1dfa-4149-af42-9cc4918c0888.png)

**Comment by linweiyuan** [comment]
因为 chatgpt-web 也是运行在容器里，那么 127.0.0.1 就会指向它自己（它自己里面并没有 go-chatgpt-api）

所以要么把两个容器放在一个 docker 网络里，用名字通信，要么把 127.0.0.1 改为 docker 自己的地址比如 172.17.0.1 （不同电脑可能会不一样）

参考我汇总的疑难杂症 issue，有对应解决方法

**Comment by lmq-118** [comment]
![image](https://user-images.githubusercontent.com/25766225/235121680-9e4908e7-f865-4546-be5d-7e7540f56d2e.png)
网络是通了，但是还是无法启动，很久没有启动起来，是不是和香港的vps有关啊 
![image](https://user-images.githubusercontent.com/25766225/235122479-76148f55-3998-4778-9137-bbec92935bec.png)

**Comment by linweiyuan** [comment]
Access denied 了

尽管看上去已经上了 warp

这个时候可以进去 warp 容器测试 curl ipinfo.io，看出来的结果在不在官方支持列表

最简单的方法就是换一台支持地的服务器，这个在我那个汇总里也有

**Comment by lmq-118** [comment]
好的， ipinfo.io 我看了，显示是我公网的IP地址，HK，估计是不行了
我试试别的吧，谢谢解答！

**Comment by linweiyuan** [comment]
curl -x socks5://127.0.0.1:40000 ipinfo.io 才能通过代理出去，不好意思我打漏了

**Comment by lmq-118** [comment]
![image](https://user-images.githubusercontent.com/25766225/235131364-6702f72b-90ce-4990-a404-0e41159b65fd.png)
这样的

**Comment by linweiyuan** [comment]
对，这个就不是自己的 IP 了

但是因为香港不在官方支持列表中，所以还是 Access denied

https://platform.openai.com/docs/supported-countries
