### ISSUE TITLE
Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by Lude-King** [linweiyuan/java-chatgpt-api#5]
有遇到这个问题吗，使用Docker-compose的默认配置启动。
`services:
  java-chatgpt-api:
    container_name: java-chatgpt-api
    image: linweiyuan/java-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - CHATGPT=true
      - PROXY=
    restart: unless-stopped`
启动后报错：
`Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Timeout 30000ms exceeded`

**Comment by linweiyuan** [comment]
需要科学上网

**Comment by Lude-King** [comment]
我用的新加坡海外服务器呢

**Comment by linweiyuan** [comment]
如果在服务器上 `curl https://chat.openai.com` 有东西返回还是卡住

有东西返回的话，那试下重启 `api`，再不行就不清楚了，可能换个节点

卡住的话，看下是否有某些配置限制了出站

**Comment by Lude-King** [comment]
谢谢，可能确实是服务器问题，换一台就可以了
