### ISSUE TITLE
docker 会出一个arm版本的吗

### ISSUE THREAD

**Issue by itcast-l** [linweiyuan/java-chatgpt-api#7]
我是部署在openwrt里面的，结果发现只有amd版本，希望能出一个arm的

**Comment by linweiyuan** [comment]
Java 这边因为用的 Firefox，不知道可不可以

但是旁边 Go 用的是 Chrome，就肯定不可以，详情可以去看那边的 issue

**Comment by xiaoguaishou92** [comment]
https://juejin.cn/post/7075225595050721310  大佬可以试试这个，看看能不能弄出来多平台镜像

**Comment by linweiyuan** [comment]
每次都是在 `./gradlew installFirefox` 中报错：

- Exception in thread "main" java.lang.ExceptionInInitializerError
- Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
- Caused by: java.lang.SecurityException: Couldn't iterate through the jurisdiction policy files: unlimited

**Comment by linweiyuan** [comment]
打了个 `arm64` 上去了：https://hub.docker.com/r/linweiyuan/java-chatgpt-api/tags

离谱，比纯打 `amd64` 多了 10 分钟

不知道能不能用，不能的话，就先放一放

**Comment by xiaoguaishou92** [comment]
> 

用那个buil x正常。非常慢。。。

**Comment by linweiyuan** [comment]
`go-chatgpt-api` 那边也有 `arm` 版本了：https://hub.docker.com/repository/docker/linweiyuan/go-chatgpt-api/tags?page=1&ordering=last_updated

内存占用几十兆，镜像几兆

`java-chatgpt-api` 这边内存占用1G，镜像解压1G，废弃了

（没有在 `arm` 设备上测试过，但感觉应该没问题）
