### ISSUE TITLE
后台自动发继续请求这个功能是失效了吗？

### ISSUE THREAD

**Issue by purepoorx** [linweiyuan/java-chatgpt-api#8]
后台自动发继续请求这个功能是失效了吗？

**Comment by linweiyuan** [comment]
有点问题，参考 #13

现在需要新传个参数

**Comment by purepoorx** [comment]
> 有点问题，参考 #13
> 
> 现在需要新传个参数

#13 在哪看，找不到了

**Comment by linweiyuan** [comment]
啊，我搞混了，go-chatgpt-api 那边的 issue #13

发过来这边没有高亮

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/issues/13

**Comment by purepoorx** [comment]
continue_text 这个参数在哪设置？环境变量吗

**Comment by linweiyuan** [comment]
这个得改客户端代码，输入问题后回车带上
