### ISSUE TITLE
运行一段时间后，请求就不回复了，日志如下

### ISSUE THREAD

**Issue by AntonRuan** [linweiyuan/java-chatgpt-api#9]
`2023-04-21T10:18:57.735Z ERROR 1 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.linweiyuan.chatgptapi.exception.ConversationException: Conversation not found] with root cause

com.linweiyuan.chatgptapi.exception.ConversationException: Conversation not found
	at com.linweiyuan.chatgptapi.service.impl.ChatGPTServiceImpl.sendConversationRequest(ChatGPTServiceImpl.java:108) ~[classes!/:1.0.0]
	at com.linweiyuan.chatgptapi.service.impl.ChatGPTServiceImpl.lambda$startConversation$0(ChatGPTServiceImpl.java:79) ~[classes!/:1.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]`

**Comment by AntonRuan** [comment]
go-chatgpt-api也是有这个问题

**Comment by linweiyuan** [comment]
`Conversation not found` 这个对话已经没了，是不是一个 `token` 多人用，然后被别人删了这个对话

**Comment by purepoorx** [comment]
我这边也存在这个问题，但并不是删除了对话。当晚还可以用的，第二天早上起来就不回复了。然而服务并没有挂掉，从日志中，可以看到当访问时，会打出这行日志 com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation  证明是有请求成功的，就是没有返回

**Comment by linweiyuan** [comment]
也会提示 `Conversation not found` ？

**Comment by purepoorx** [comment]
> 

不会提示，但这个提示我也遇到过，是在https://chat.openai.com上把对应的会话删除了，就会提示Conversation not found。我遇到的不是这个问题，是长时间不使用，然后再次调用，就会没有返回信息

**Comment by purepoorx** [comment]
只有重启服务才行

**Comment by linweiyuan** [comment]
像是发生了死锁，能有一个比较准确能触发这个 bug 的步骤吗

**Comment by purepoorx** [comment]
一个晚上不用这个自建代理，第二天100%触发这个bug

**Comment by linweiyuan** [comment]
除了对话，其他接口正不正常

**Comment by purepoorx** [comment]
这个我就不清楚了，是直接用前端chatgpt-web调用的自建代理  http://xxxxxx/conversation。。自建代理没有看到异常日志

**Comment by xiaoguaishou92** [comment]
同样问题，我用crontab做了一个两小时自动重启的任务

**Comment by linweiyuan** [comment]
我用最新的镜像挂了一天，隔一两个小时请求一次，无法复现

**Comment by purepoorx** [comment]
隔十个小时再请求，就会复现了，一两个小时间隔太短了

**Comment by linweiyuan** [comment]
其实有点没理由，访问无响应无非就是死锁了

对话开始加锁结束释放，每分钟自动刷新前加锁刷新完释放

理论上出现在这俩地方

**Comment by linweiyuan** [comment]
环境变量加上 `DEBUG=pw:api`，可输出多一点日志

**Comment by linweiyuan** [comment]
我在 Go 那个项目试出来了，其实是刷新浏览器的时候一直卡住在转，卡很久都没法完成刷新，这样就无法刷新 Cookie，导致锁没释放

需要看看怎么处理

**Comment by purepoorx** [comment]
对的，go和java两个项目都有这个问题

**Comment by AntonRuan** [comment]
坐等大佬解决

**Comment by linweiyuan** [comment]
今天把那些锁，死循环都去掉了，有兴趣可以拉下最新镜像今晚测试下

**Comment by AntonRuan** [comment]
今天跑了一天，没出问题，多谢大佬。
